
#ifndef H_SYMPHONY_COMMANDS_TEDIT
#define H_SYMPHONY_COMMANDS_TEDIT

#include "command.h"

DEF_COMMAND(TCmdAppend)
DEF_COMMAND(TCmdCancel)
DEF_COMMAND(TCmdClear)
DEF_COMMAND(TCmdDelete)
DEF_COMMAND(TCmdInsert)
DEF_COMMAND(TCmdReplace)
DEF_COMMAND(TCmdSend)
DEF_COMMAND(TCmdShow)

#endif // #ifndef H_SYMPHONY_COMMANDS_TEDIT
