
#ifndef H_SYMPHONY_COMMANDS_REDIT
#define H_SYMPHONY_COMMANDS_REDIT

#include "command.h"

DEF_COMMAND(RCmdCreate)
DEF_COMMAND(RCmdDelete)
DEF_COMMAND(RCmdDescription)
DEF_COMMAND(RCmdDig)
DEF_COMMAND(RCmdExitflag)
DEF_COMMAND(RCmdFlag)
DEF_COMMAND(RCmdInformation)
DEF_COMMAND(RCmdKey)
DEF_COMMAND(RCmdLink)
DEF_COMMAND(RCmdName)
DEF_COMMAND(RCmdSmell)
DEF_COMMAND(RCmdSound)
DEF_COMMAND(RCmdTerrain)
DEF_COMMAND(RCmdUnlink)

#endif // #ifndef H_SYMPHONY_COMMANDS_REDIT
